### ISSUE TITLE
Sonatype snapshots not present

### ISSUE THREAD

**Issue by fommil** [cibuddy/cibuddy#22]
I tried to use the drivers as a dependency, but the following fails

```
    <repositories>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.cibuddy</groupId>
            <artifactId>drivers</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
```

because Maven expects to see a file here

``
https://oss.sonatype.org/content/repositories/snapshots/com/cibuddy/drivers/1.0-SNAPSHOT/drivers-1.0-SNAPSHOT.jar

```

which doesn't exist.
```

**Comment by mirkojahn** [comment]
That's correct. "drivers" is just a parent pom. The actual driver is in the folder below (I intended to include not only a HID driver, but potentially others like serial for instance). Try this one instead (extra "0" in the version is important unfortunately):

```
<dependencies>
        <dependency>
            <groupId>com.cibuddy</groupId>
            <artifactId>hid</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
</dependencies>
```

**Comment by fommil** [comment]
@mirkojahn cool! But what's your equivalent of `ClassPathLibraryLoader.loadNativeHIDLibrary();` ?

**Comment by mirkojahn** [comment]
I am currently trying to build a new version that contains the respective ClassPathLoader. In the OSGi context, you don't need that one, so I didn't include it in the first place. I am still not shipping the Test and Applet classes, because for those I don't see a use case in terms of being reusable artifacts, but I am open for examples that convince me otherwise :-) As soon as my deployment to the maven repository is finished, you should be able to consume the jar like the one from codeminders (just make sure your maven is not caching the old version -> call it with "-U")

**Comment by mirkojahn** [comment]
Ok, the deployment just finished... Let me know how it went.

**Comment by fommil** [comment]
Smashing, worked! I'll let you know if my Raspberry Pi users have problems.
